version: "3"
services:
  mysql:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-mysqldb}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-mysql}

volumes:
  dbdata: